# This image is built as a single platform image with media type application/vnd.docker.distribution.manifest.v2+json
FROM scratch
LABEL org.opencontainers.image.source=https://github.com/apple/containerization
# empty add so that the build doesn't error due to no build directives
ADD . .
